### PR TITLE
the images folder is missing

### PR DESCRIPTION
**Pull request by AlainRnet**
and there's no picture in module's description

### CODE REVIEW

**Comment by AlainRnet** [comment]
and leaflet folder is missing too

**Comment by Schlumpf** [comment]
The folders are listed in the "media" section. So they are installed to /media/mod_osmod.
You don't see a description image? Which version do you use?

**Comment by AlainRnet** [comment]
Thanks for very fast answer.
I think I use last version : 2.14
Source code is "../modules/mod_osmod/images/custom_marker_help.png" so I think language file has an error...
What do you think ?

**Comment by Schlumpf** [comment]
The latest version is v2.13. Where did you find v2.14?

**Comment by AlainRnet** [comment]
Yes, I use French version.
Thank you for the link and new package, it works fine!
I just have a problem with the accented letters in your module's message after installation:

> Affiche OpenStreetMap avec des �pingles (point d'int�r�ts).
> Suppression
>  des fichiers obsol�tes...
>  R�alis�.
>  OSModul mis � jour en version 2.14.
>  Please note, the support for MapQuest has been dropped.

Best regards.

**Comment by Schlumpf** [comment]
Should be fixed in v2.14.
Please reopen if no ;)

**Pull request closed without merging**
