### PR TITLE
Max/Min Zoom

### PR DESCRIPTION
**Pull request by efduggan**
- added min/max zoom levels to main map.
- added translations for comments that were in German

### CODE REVIEW

**Comment by Schlumpf** [comment]
Hi, thanks for zour

**Comment by Schlumpf** [comment]
Hi @efduggan,
thanks for your interest in improving OSModul. Your help is welcome :)

Since you said, you new to git, here are some tips:
 - please split your changes in serval PRs (pull requsts). This gives the opportunity to merge the changes individually. For example, your update to Leaflet 1.0.3 is correct, and I would like to merge it into master. But your comment translation need some correction. If there are several different changes in one PR, I cannot merge, until all are ready to merge. Usually you pull the master and create several branches form the master for each topic (Update, translation, ...). There branches will become different PRs.
 - You need not mark all your changes by EFD, the git history shows, who made the changes.

Please spilt your PR, than I can review and merge it. I merged the interaction branch into master, so maybe you can use this as a start point. If you are done, we can publish v2.14 including your changes.

Best regards
Martin

**Comment by efduggan** [comment]
Hi Martin,

thanks for the welcome. I'm still wrapping my head around GIT/GITHub so I really appreciate your comments. I've started using GITHub desktop so hopefully that works better for me, as I could not upload multiple files into one commit. 

I'll attempt to split the PR today so that you can merge in the 1.0.3 Leaflet Library. 

regards,
Edmond

**Comment by efduggan** [comment]
I've not found any way to split a Pull Request, either in GITHub or GITHub Desktop. Perhaps a screenshare sometime to explain how to do this task?

regards,
Edmond

**Comment by Schlumpf** [comment]
I don't know GitHub Desktop. I'm a command line user ;)
Here are the steps, I would try, it should be possible with all guis:
 - fetch upstream/master. Than you have the current state of the "official" repo.
 - checkout upstream/master. Than your working dir changes to that version.
 - create a new branch "leaflet-update" at the top of upstream/master.
 - cherry-pick the commits from your local master branch, which update the Leaflet lib.
 - checkout upstream/master. Switch back to that "current official" version.

For further features, always create a new branch on top of current upstream/master an develop every feature/bugfix in a separate branch. In result, you can have different PRs pending and work on new ones.

I hope, I could help you a bit...

**Comment by efduggan** [comment]
Thanks - I'm going to start fresh and see if things go better. As far as I can tell it will require me to delete my copy, so these comments may be lost. I'll do that tomorrow so you at least have some time to see this post :-)

**Comment by efduggan** [comment]
closing as I’ll split this work up into individual pull requests

**Pull request closed without merging**
